apiVersion: apps/v1
kind: Deployment
metadata:
  name: my1app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my1app
  template:
    metadata:
      labels:
        app: my1app
    spec:
      containers:
        - name: my1app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
{{- toYaml .Values.resources | nindent 12 }}
