{{- if .Values.prometheus.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my1app
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: my1app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
