replicaCount: 1

image:
  repository: 507363615947.dkr.ecr.eu-central-1.amazonaws.com/myapp-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

prometheus:
  servicemonitor:
    enabled: true
