replicaCount: 1

image:
  repository: my1app-image-repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

prometheus:
  servicemonitor:
    enabled: true
