name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Setup Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${KUBECONFIG}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      env:
        TF_VAR_namespace: "default"
        TF_VAR_image_repository: "myapp-image-repo"
        TF_VAR_image_tag: "latest"
      run: terraform plan -out=tfplan
      working-directory: terraform

    - name: Terraform Apply
      env:
        TF_VAR_namespace: "default"
        TF_VAR_image_repository: "myapp-image-repo"
        TF_VAR_image_tag: "latest"
      run: terraform apply -auto-approve
      working-directory: terraform
